# Generated by Django 5.2.14 on 2026-05-30 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0010_customuser_must_change_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bs_date",
                    models.CharField(
                        help_text="BS date as YYYY/MM/DD e.g. 2083/06/24", max_length=10
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nepali / Devanagari name", max_length=255
                    ),
                ),
                (
                    "remarks",
                    models.CharField(
                        blank=True,
                        help_text="English remark or context",
                        max_length=255,
                    ),
                ),
                (
                    "is_holiday",
                    models.BooleanField(
                        default=True, help_text="Government public holiday"
                    ),
                ),
                (
                    "is_optional",
                    models.BooleanField(
                        default=False, help_text="Optional / cultural day"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["bs_date"],
            },
        ),
        migrations.CreateModel(
            name="HolidaySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("range_start", models.CharField(default="2083/02/15", max_length=10)),
                ("range_end", models.CharField(default="2084/03/32", max_length=10)),
                ("period_label", models.CharField(blank=True, max_length=120)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Holiday Settings",
                "verbose_name_plural": "Holiday Settings",
            },
        ),
    ]
