# Generated by Django 5.2.14 on 2026-06-01 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0012_alter_book_isbn"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="targets",
            field=models.ManyToManyField(
                blank=True,
                help_text="Optional: target this announcement to specific staff members (overrides audience for those staff).",
                related_name="announcements",
                to="main_app.staff",
            ),
        ),
        migrations.CreateModel(
            name="Clearance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(0, "Pending"), (1, "Approved"), (-1, "Rejected")],
                        default=0,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_app.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
