# Generated by Django 5.2.14 on 2026-06-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0013_announcement_targets_clearance"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="date_of_join",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="staff",
            name="department",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="staff",
            name="division",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="staff",
            name="duty_shift",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="staff",
            name="employment_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("full_time", "Full Time"),
                    ("part_time", "Part Time"),
                    ("contract", "Contract"),
                ],
                default="full_time",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="last_promotion_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="staff",
            name="permanent_on",
            field=models.DateField(blank=True, null=True),
        ),
    ]
