# Generated by Django 5.2.14 on 2026-06-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "main_app",
            "0014_staff_date_of_join_staff_department_staff_division_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="contact_number",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
