# Generated by Django 5.2.14 on 2026-06-01 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0015_staff_contact_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeEducationDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("slc", "SLC"),
                            ("intermediate", "Intermediate"),
                            ("bachelor", "Bachelor"),
                            ("master", "Master"),
                            ("phd", "PhD"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "title_of_qualification",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "institution",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("passed_year", models.IntegerField(blank=True, null=True)),
                (
                    "percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "specialization",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education_details",
                        to="main_app.staff",
                    ),
                ),
            ],
            options={
                "ordering": ["-passed_year"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeIdentificationDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank_name", models.CharField(blank=True, default="", max_length=200)),
                (
                    "account_number",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "citizenship_number",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("citizenship_issue_date", models.DateField(blank=True, null=True)),
                (
                    "citizenship_issue_place",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("pf_number", models.CharField(blank=True, default="", max_length=50)),
                ("cit_number", models.CharField(blank=True, default="", max_length=50)),
                ("pan_number", models.CharField(blank=True, default="", max_length=50)),
                (
                    "blood_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("O+", "O+"),
                            ("O-", "O-"),
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "staff",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identification_details",
                        to="main_app.staff",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeePromotionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "promotion_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("internal", "Internal"),
                            ("external", "External"),
                            ("lateral", "Lateral"),
                        ],
                        default="internal",
                        max_length=20,
                    ),
                ),
                (
                    "from_level",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("to_level", models.CharField(blank=True, default="", max_length=200)),
                ("unpaid_leaves", models.IntegerField(default=0)),
                ("remarks", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotion_history",
                        to="main_app.staff",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeTransferHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transfer_date", models.DateField()),
                (
                    "from_department",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "to_department",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "transfer_type",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("remarks", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfer_history",
                        to="main_app.staff",
                    ),
                ),
            ],
            options={
                "ordering": ["-transfer_date"],
            },
        ),
    ]
