# Generated by Django 5.2.14 on 2026-06-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0016_employeeeducationdetails_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="hr_extra_details",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
