# Generated by Django 5.2.14 on 2026-06-01 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0017_staff_hr_extra_details"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="subject",
        ),
        migrations.CreateModel(
            name="BiometricLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("in_time", models.TimeField(blank=True, null=True)),
                ("out_time", models.TimeField(blank=True, null=True)),
                ("in_timestamp", models.DateTimeField(blank=True, null=True)),
                ("out_timestamp", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="biometric_logs",
                        to="main_app.staff",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-in_timestamp"],
                "unique_together": {("staff", "date")},
            },
        ),
        migrations.CreateModel(
            name="EmployeeAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("late", "Late"),
                            ("early_out", "Early Out"),
                            ("half_day", "Half Day"),
                            ("leave", "Leave"),
                        ],
                        default="absent",
                        max_length=20,
                    ),
                ),
                ("in_time", models.TimeField(blank=True, null=True)),
                ("out_time", models.TimeField(blank=True, null=True)),
                (
                    "worked_hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("late_by_minutes", models.IntegerField(default=0)),
                ("early_out_by_minutes", models.IntegerField(default=0)),
                ("remarks", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_attendance_records",
                        to="main_app.staff",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("staff", "date")},
            },
        ),
    ]
