# Generated by Django 5.2.14 on 2026-06-01 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0020_attendance_subject_alter_inventoryitem_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="purchase_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1, help_text="Number of copies / accession count"
            ),
        ),
        migrations.CreateModel(
            name="ClearanceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requested_on", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(0, "Pending"), (1, "Approved"), (-1, "Rejected")],
                        default=0,
                    ),
                ),
                ("remarks", models.TextField(blank=True, default="")),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clearance_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_on"],
            },
        ),
    ]
