# Generated by Django 5.2.14 on 2026-06-02 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0021_book_purchase_date_book_quantity_clearancerequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("late", "Late"),
                            ("early_out", "Early Out"),
                            ("half_day", "Half Day"),
                            ("leave", "Leave"),
                        ],
                        default="absent",
                        max_length=20,
                    ),
                ),
                ("in_time", models.TimeField(blank=True, null=True)),
                ("out_time", models.TimeField(blank=True, null=True)),
                (
                    "worked_hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("late_by_minutes", models.IntegerField(default=0)),
                ("early_out_by_minutes", models.IntegerField(default=0)),
                ("remarks", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="biometriclog",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="biometriclog",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="biometric_logs",
                to="main_app.student",
            ),
        ),
        migrations.AlterField(
            model_name="biometriclog",
            name="staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="biometric_logs",
                to="main_app.staff",
            ),
        ),
        migrations.AddConstraint(
            model_name="biometriclog",
            constraint=models.UniqueConstraint(
                condition=models.Q(("staff__isnull", False)),
                fields=("staff", "date"),
                name="unique_staff_date_biometric",
            ),
        ),
        migrations.AddConstraint(
            model_name="biometriclog",
            constraint=models.UniqueConstraint(
                condition=models.Q(("student__isnull", False)),
                fields=("student", "date"),
                name="unique_student_date_biometric",
            ),
        ),
        migrations.AddField(
            model_name="studentattendance",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_attendance_records",
                to="main_app.student",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentattendance",
            unique_together={("student", "date")},
        ),
    ]
